name: "Deployment Request"
description: "Request to deploy CreateX on a new chain."
title: "[New-Deployment-Request]: "
labels:
  - new deployment âž•
assignees:
  - pcaversaccio
body:
  - type: markdown
    attributes:
      value: |
        Before opening a deployment request, consider deploying CreateX yourself.
        See the README section [New Deployment(s)](https://github.com/pcaversaccio/createx#new-deployments) for more information about how to do this.

  - attributes:
      label: Chain Name
      description: What is the name of the target chain?
      placeholder: "Optimism Mainnet"
    id: chain-name
    type: input
    validations:
      required: true

  - attributes:
      label: Chain ID
      description: What is the chain ID of the target chain?
      placeholder: "10"
    id: chain-id
    type: input
    validations:
      required: true

  - attributes:
      label: RPC URL
      description: What is the RPC URL for the target chain?
      placeholder: "https://mainnet.optimism.io"
    id: rpc-url
    type: input
    validations:
      required: true

  - attributes:
      label: Block Explorer URL
      description: What is the URL of the block explorer for the target chain?
      placeholder: "https://optimistic.etherscan.io"
    id: block-explorer-url
    type: input
    validations:
      required: true

  - attributes:
      label: Deployment Funds
      description: |
        Have you sent the deployment funds to the deployer account (TBD) on the target chain?
        Doing so is greatly appreciated and will reduce time to deployment!
      options:
        - "Yes"
        - "No"
    id: deployment-funds
    type: dropdown
    validations:
      required: true
